from datetime import datetime, timezone
from typing import List, Literal, Optional

from beanie import Document
from pydantic import Field


class Meeting(Document):
    # Human-readable meeting title shown in dashboard lists; defaults on creation.
    title: str = "Untitled Meeting"

    # Meeting lifecycle status; starts as active and becomes ended when the meeting finishes.
    status: Literal["active", "ended"] = "active"

    # Timestamp set when the meeting document is created.
    started_at: datetime = Field(default_factory=lambda: datetime.now(timezone.utc))

    # Timestamp populated only when the meeting is ended.
    ended_at: Optional[datetime] = None

    # Number of participants currently associated with the meeting session.
    participant_count: int = 1

    # Running counter of transcript chunks; incremented as streaming chunks arrive.
    transcript_chunks: int = 0

    # AI-generated summary bullet points, refreshed periodically during the meeting.
    summary_bullets: List[str] = Field(default_factory=list)

    # Additional structured summary fields generated by AI.
    key_decisions: List[str] = Field(default_factory=list)
    open_questions: List[str] = Field(default_factory=list)

    # Count of extracted action items, updated as analysis jobs produce tasks.
    action_items_count: int = 0

    # Flag indicating conflicting statements/decisions were detected in analysis.
    has_conflict: bool = False
    conflict_message: Optional[str] = None

    # Full end-of-meeting debrief payload, populated after the meeting ends.
    debrief: Optional[dict] = None

    class Settings:
        name = "meetings"

    @classmethod
    async def get_active(cls) -> Optional["Meeting"]:
        """Return the most recently started active meeting, if one exists."""
        return await cls.find(cls.status == "active").sort([("started_at", -1)]).first_or_none()
